USE STUDENTS;

CREATE TABLE EMPLOYEE_DATA (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    AGE INT NOT NULL,
    CITY VARCHAR (50) NOT NULL,
    SALARY INT DEFAULT 500000,
    CHECK (AGE >= 18) 
);

INSERT INTO EMPLOYEE_DATA (NAME, AGE, CITY,SALARY)
VALUES ('Miraj Sankdecha', 20, 'Rajkot', 900000);
